"""Configuration constants for workshop-watcher."""

# Discord Limits
DISCORD_MAX_EMBEDS_PER_MESSAGE = 10
DISCORD_EMBED_TITLE_MAX_DISPLAY = 100
DISCORD_EMBED_DESC_MAX_DISPLAY = 200
DISCORD_EMBED_MAX_SIZE = 5000  # Warn threshold
DISCORD_EMBED_HARD_LIMIT = 6000

# Discord embed field limits (official limits)
DISCORD_EMBED_TITLE_LIMIT = 256
DISCORD_EMBED_DESCRIPTION_LIMIT = 4096
DISCORD_EMBED_TOTAL_LIMIT = 6000

# Steam API Limits
STEAM_WORKSHOP_BATCH_SIZE = 50
STEAM_USER_BATCH_SIZE = 100
STEAM_API_TIMEOUT = 20

# Caching
USER_CACHE_TTL_SECONDS = 7 * 24 * 60 * 60  # 7 days

# Retry Configuration
MAX_DISCORD_RETRIES = 5
MAX_RETRY_DELAY_SECONDS = 60  # Max exponential backoff
SERVER_ERROR_RETRY_DELAY_SECONDS = 30  # Max for 5xx errors
